### ISSUE TITLE
Suggestion: support for Fabric versions below 0.14.14

### ISSUE THREAD

**Issue by BetaKors** [chloecdn/cdn-perspective-3d#1]
Support for Fabric v0.14.13 in particular would allow this mod to be used with the most recent version of Quilt as well. Not sure if this is viable, so it's just a suggestion.

**Comment by LunaticWasTaken** [comment]
you can easily change the required loader-version inside the mod.json.
just change [this](https://github.com/chloecdn/cdn-perspective-3d/blob/cab1d75e7a5149201eb13c18a078a60316e50414/src/main/resources/fabric.mod.json#L25) to whatever version you need as a minimum. for example `>=0.14.13` works on 0.14.13 and above. or just use `*` to allow every version.

If you cant compile it yourself, just change it inside the jar-file itself.

**Comment by LunaticWasTaken** [comment]
also sorry for the late answer, github for some reason is a dick and doesnt give me any notifications :/
